import type {
  BodyCondition,
  BodyPartCondition,
  ExpertiseReport,
  Reminder,
  Vehicle,
  VehicleDocument,
  VehicleNote,
  VehicleRecord,
} from '@/domain/entities';
import { bodyConditionLabels } from '@/features/bodyCondition/config/bodyConditions';
import { bodySchemas } from '@/features/bodyCondition/schemas';
import { documentTypeLabels } from '@/features/documents/config/documentTypes';
import { getDocumentStatus } from '@/features/documents/domain/documentStatus';
import { getFuelStationLabel } from '@/features/fuel/config/fuelStations';
import { getBodySchemaType, getVehicleBodyTypeLabel } from '@/features/vehicles/config/bodyTypes';
import { getVehicleColorLabel } from '@/features/vehicles/config/vehicleColors';
import { fuelTypeLabels } from '@/shared/constants/labels';
import { getReminderDisplay } from '@/shared/utils/analytics';
import { formatCurrency, formatDate, formatNumber, todayDateOnly } from '@/shared/utils/format';
import { buildVehicleReport, type ReportPeriodId, type VehicleReport } from '../domain/vehicleReports';

/**
 * The print document model.
 *
 * Everything here is derived deterministically from records the user already
 * has. No value is inferred, estimated or generated by a model — the PDF is an
 * official-looking record, so an invented number would be worse than an absent
 * one. Unknown values become an explicit dash rather than a zero.
 */

export const REPORT_PDF_MAX_ROWS = 15;

export interface ReportField {
  label: string;
  value: string;
}

export interface ReportTableRow {
  cells: string[];
}

export interface ReportBodyPart {
  key: string;
  label: string;
  /** SVG path from the shared body schema; the PDF draws real line-art, not a screenshot. */
  path: string;
  condition: BodyCondition | null;
  conditionLabel: string;
  note: string | null;
}

export interface ReportDistributionSlice {
  label: string;
  amount: number;
  formattedAmount: string;
  sharePercent: number;
}

export interface ReportTrendPoint {
  label: string;
  total: number;
  formattedTotal: string;
  /** 0-100, relative to the tallest bar; the PDF chart is plain sized divs. */
  heightPercent: number;
}

export interface VehicleReportDocument {
  title: string;
  generatedAtLabel: string;
  periodLabel: string;
  vehicleHeading: string;
  identity: ReportField[];
  summary: ReportField[];
  trend: ReportTrendPoint[];
  distribution: ReportDistributionSlice[];
  maintenanceRows: ReportTableRow[];
  maintenanceTruncated: boolean;
  fuelRows: ReportTableRow[];
  fuelTruncated: boolean;
  bodySchema: { silhouettePath: string; windshieldPath: string; rearWindowPath: string };
  bodyParts: ReportBodyPart[];
  bodyConditionCounts: { label: string; count: number }[];
  expertiseSummary: ReportField[];
  expertiseNotes: string[];
  documentSummary: ReportField[];
  expiringDocuments: ReportTableRow[];
  overdueReminders: ReportTableRow[];
  upcomingReminders: ReportTableRow[];
  missingIdentityFields: string[];
  noteHighlights: { title: string; content: string }[];
}

export interface VehicleReportDocumentInput {
  vehicle: Vehicle;
  records: VehicleRecord[];
  reminders: Reminder[];
  bodyConditions: BodyPartCondition[];
  documents: VehicleDocument[];
  expertiseReports: ExpertiseReport[];
  notes: VehicleNote[];
  periodId: ReportPeriodId;
  /** Reuses the value the reports dashboard already computed when available. */
  report?: VehicleReport;
  now?: Date;
}

const DASH = '—';

function optionalText(value: string | null | undefined): string {
  const trimmed = value?.trim();
  return trimmed ? trimmed : DASH;
}

function optionalNumber(value: number | null | undefined, suffix = ''): string {
  return typeof value === 'number' && Number.isFinite(value)
    ? `${formatNumber(value)}${suffix}`
    : DASH;
}

function formatLongDateTime(now: Date): string {
  return new Intl.DateTimeFormat('tr-TR', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  }).format(now);
}

function byDateDescending<T extends { recordDate: string }>(rows: readonly T[]): T[] {
  return [...rows].sort((left, right) => right.recordDate.localeCompare(left.recordDate));
}

function maintenanceLabel(record: VehicleRecord): string {
  return (
    record.serviceName?.trim() ||
    record.maintenanceItems?.[0]?.itemType?.trim() ||
    record.category?.trim() ||
    'Bakım'
  );
}

export function buildVehicleReportDocument(
  input: VehicleReportDocumentInput,
): VehicleReportDocument {
  const now = input.now ?? new Date();
  const today = todayDateOnly();
  const { vehicle } = input;
  const scopedRecords = input.records.filter((record) => record.vehicleId === vehicle.id);
  const report =
    input.report ?? buildVehicleReport(scopedRecords, vehicle, input.periodId, now);

  const identity: ReportField[] = [
    { label: 'Marka', value: optionalText(vehicle.brand) },
    { label: 'Model', value: optionalText(vehicle.model) },
    { label: 'Model yılı', value: vehicle.year !== null ? String(vehicle.year) : DASH },
    { label: 'Plaka', value: optionalText(vehicle.plate) },
    { label: 'Renk', value: getVehicleColorLabel(vehicle.colorId, vehicle.color) },
    { label: 'Yakıt tipi', value: fuelTypeLabels[vehicle.fuelType] ?? DASH },
    { label: 'Kasa tipi', value: getVehicleBodyTypeLabel(vehicle.bodyType) },
    { label: 'Güncel kilometre', value: `${formatNumber(vehicle.currentKm)} km` },
  ];

  const openReminders = input.reminders.filter(
    (reminder) => reminder.vehicleId === vehicle.id && !reminder.completed,
  );
  const reminderStates = openReminders.map((reminder) => ({
    reminder,
    display: getReminderDisplay(reminder, vehicle.currentKm, today),
  }));
  const overdue = reminderStates.filter((entry) =>
    ['date_overdue', 'mileage_overdue', 'both_overdue'].includes(entry.display.status),
  );
  const upcoming = reminderStates.filter((entry) =>
    ['approaching', 'today', 'mileage_due'].includes(entry.display.status),
  );

  const summary: ReportField[] = [
    { label: 'Toplam kayıtlı harcama', value: formatCurrency(report.totalCost) },
    { label: 'Yakıt harcaması', value: formatCurrency(report.fuelCost) },
    { label: 'Bakım harcaması', value: formatCurrency(report.maintenanceCost) },
    { label: 'Diğer harcamalar', value: formatCurrency(report.otherCost) },
    { label: 'Toplam yakıt', value: optionalNumber(report.fuelLiters, ' L') },
    {
      label: 'Ortalama litre fiyatı',
      value: report.averageFuelPrice === null ? DASH : formatCurrency(report.averageFuelPrice),
    },
    { label: 'Kayıtlı bakım sayısı', value: String(report.maintenanceCount) },
    { label: 'Açık hatırlatıcı', value: `${openReminders.length} (${overdue.length} gecikmiş)` },
  ];

  const trendMax = Math.max(...report.buckets.map((bucket) => bucket.total), 0);
  const trend: ReportTrendPoint[] = report.buckets.map((bucket) => ({
    label: bucket.label,
    total: bucket.total,
    formattedTotal: formatCurrency(bucket.total),
    heightPercent: trendMax > 0 ? Math.round((bucket.total / trendMax) * 100) : 0,
  }));

  const distributionTotal = report.fuelCost + report.maintenanceCost + report.otherCost;
  const distribution: ReportDistributionSlice[] = (
    [
      ['Yakıt', report.fuelCost],
      ['Bakım', report.maintenanceCost],
      ['Diğer', report.otherCost],
    ] as const
  )
    .filter(([, amount]) => amount > 0)
    .map(([label, amount]) => ({
      label,
      amount,
      formattedAmount: formatCurrency(amount),
      sharePercent: distributionTotal > 0 ? Math.round((amount / distributionTotal) * 100) : 0,
    }));

  const periodRecords = scopedRecords.filter(
    (record) => record.recordDate >= report.period.start && record.recordDate <= report.period.end,
  );
  const maintenanceRecords = byDateDescending(
    periodRecords.filter((record) => record.recordType === 'maintenance'),
  );
  const fuelRecords = byDateDescending(
    periodRecords.filter((record) => record.recordType === 'fuel'),
  );

  const maintenanceRows: ReportTableRow[] = maintenanceRecords
    .slice(0, REPORT_PDF_MAX_ROWS)
    .map((record) => ({
      cells: [
        formatDate(record.recordDate),
        record.kilometer === null ? DASH : `${formatNumber(record.kilometer)} km`,
        maintenanceLabel(record),
        formatCurrency(record.amount),
      ],
    }));

  const fuelRows: ReportTableRow[] = fuelRecords.slice(0, REPORT_PDF_MAX_ROWS).map((record) => ({
    cells: [
      formatDate(record.recordDate),
      record.liters === null ? DASH : `${formatNumber(record.liters, 2)} L`,
      record.pricePerLiter ? formatCurrency(record.pricePerLiter) : DASH,
      formatCurrency(record.amount),
      optionalText(getFuelStationLabel(record.stationBrand)),
    ],
  }));

  const schema = bodySchemas[getBodySchemaType(vehicle.bodyType)];
  const conditionByPart = new Map(
    input.bodyConditions
      .filter((entry) => entry.vehicleId === vehicle.id)
      .map((entry) => [entry.partKey, entry]),
  );
  const bodyParts: ReportBodyPart[] = schema.parts.map((part) => {
    const stored = conditionByPart.get(part.key);
    return {
      key: part.key,
      label: part.label,
      path: part.path,
      condition: stored?.condition ?? null,
      conditionLabel: stored ? bodyConditionLabels[stored.condition] : 'Kayıt yok',
      note: stored?.note?.trim() || null,
    };
  });
  const conditionCounts = new Map<string, number>();
  for (const part of bodyParts) {
    const key = part.conditionLabel;
    conditionCounts.set(key, (conditionCounts.get(key) ?? 0) + 1);
  }
  const bodyConditionCounts = [...conditionCounts]
    .map(([label, count]) => ({ label, count }))
    .sort((left, right) => right.count - left.count);

  const vehicleExpertise = input.expertiseReports.filter(
    (entry) => entry.vehicleId === vehicle.id,
  );
  const latestExpertise = [...vehicleExpertise].sort((left, right) =>
    String(right.reportDate ?? '').localeCompare(String(left.reportDate ?? '')),
  )[0];
  const expertiseSummary: ReportField[] = [
    { label: 'Kayıtlı ekspertiz raporu', value: String(vehicleExpertise.length) },
    { label: 'Son rapor tarihi', value: latestExpertise?.reportDate ? formatDate(latestExpertise.reportDate) : DASH },
    { label: 'Kurum', value: optionalText(latestExpertise?.companyName) },
  ];
  const expertiseNotes = vehicleExpertise
    .map((entry) => entry.overallNote?.trim())
    .filter((note): note is string => Boolean(note))
    .slice(0, 3);

  const vehicleDocuments = input.documents.filter((entry) => entry.vehicleId === vehicle.id);
  const documentStatuses = vehicleDocuments.map((entry) => ({
    document: entry,
    status: getDocumentStatus(entry.expiryDate, today),
  }));
  const documentTypeCount = new Set(vehicleDocuments.map((entry) => entry.documentType)).size;
  const documentSummary: ReportField[] = [
    { label: 'Kayıtlı belge', value: String(vehicleDocuments.length) },
    { label: 'Belge türü', value: String(documentTypeCount) },
    {
      label: 'Süresi dolmuş',
      value: String(documentStatuses.filter((entry) => entry.status === 'expired').length),
    },
    {
      label: 'Yaklaşan son kullanma',
      value: String(documentStatuses.filter((entry) => entry.status === 'expiring_soon').length),
    },
  ];
  const expiringDocuments: ReportTableRow[] = documentStatuses
    .filter((entry) => entry.status === 'expiring_soon' || entry.status === 'expired')
    .sort((left, right) =>
      String(left.document.expiryDate ?? '').localeCompare(String(right.document.expiryDate ?? '')),
    )
    .slice(0, REPORT_PDF_MAX_ROWS)
    .map((entry) => ({
      cells: [
        documentTypeLabels[entry.document.documentType] ?? entry.document.documentType,
        optionalText(entry.document.title),
        formatDate(entry.document.expiryDate),
        entry.status === 'expired' ? 'Süresi doldu' : 'Yaklaşıyor',
      ],
    }));

  const reminderRow = (entry: (typeof reminderStates)[number]): ReportTableRow => ({
    cells: [
      entry.reminder.title,
      entry.reminder.dueDate ? formatDate(entry.reminder.dueDate) : DASH,
      entry.reminder.dueKilometer === null
        ? DASH
        : `${formatNumber(entry.reminder.dueKilometer)} km`,
      entry.display.reasons.join(' · ') || DASH,
    ],
  });

  const missingIdentityFields = identity
    .filter((field) => field.value === DASH || field.value === 'Renk belirtilmedi')
    .map((field) => field.label);

  const noteHighlights = input.notes
    .filter((note) => note.vehicleId === vehicle.id)
    .sort((left, right) => right.updatedAt.localeCompare(left.updatedAt))
    .slice(0, 3)
    .map((note) => ({ title: note.title, content: note.content }));

  return {
    title: 'Araç Geçmiş ve Durum Raporu',
    generatedAtLabel: formatLongDateTime(now),
    periodLabel: report.period.label,
    vehicleHeading: `${vehicle.brand} ${vehicle.model}`.trim(),
    identity,
    summary,
    trend,
    distribution,
    maintenanceRows,
    maintenanceTruncated: maintenanceRecords.length > REPORT_PDF_MAX_ROWS,
    fuelRows,
    fuelTruncated: fuelRecords.length > REPORT_PDF_MAX_ROWS,
    bodySchema: {
      silhouettePath: schema.silhouettePath,
      windshieldPath: schema.windshieldPath,
      rearWindowPath: schema.rearWindowPath,
    },
    bodyParts,
    bodyConditionCounts,
    expertiseSummary,
    expertiseNotes,
    documentSummary,
    expiringDocuments,
    overdueReminders: overdue.map(reminderRow),
    upcomingReminders: upcoming.map(reminderRow),
    missingIdentityFields,
    noteHighlights,
  };
}
